//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2017-09-28 14:27:14 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4.Entities
{    

    public class X6_Organization_DepartmentAdjust
    {
        
        /// <summary>
        /// 
        /// </summary>        
        public string Code { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string DepartmentName { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? CompanyId { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? ParentDepartmentId { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string AdjustedCode { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string AdjustedDepartmentName { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? AdjustedParentCompanyId { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? AdjustedParentDepartmentId { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? AdjustedDate { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Regulator { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid VGUID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Status { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? IsDeleted { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? Sort { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Founder { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? CreateTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ModifiedBy { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? ModifiedTime { get; set; }
         
      
    }
}
