//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2017-10-31 16:59:37 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4.Entities
{    

    public class X6_Personnel_BasicInfo_DataInformationList
    {
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? HandBook { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? LaborContract { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? ConfidentialityAgreement { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? EducationProve { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? ResignationCertificate { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? IDCopy { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? BackCardCopy { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? CriminalRecordProve { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? HealthReport { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? Qualification { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public bool? BirthReport { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid? BasicInfoId { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public Guid VGUID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? IsDeleted { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public int? Sort { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string Founder { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? CreateTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ModifiedBy { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public DateTime? ModifiedTime { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string HandBookAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string LaborContractAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ConfidentialityAgreementAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string EducationProveAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string ResignationCertificateAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string IDCopyAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string BackCardCopyAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string CriminalRecordProveAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string HealthReportAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string QualificationAccessory { get; set; }
        
        /// <summary>
        /// 
        /// </summary>        
        public string BirthReportAccessory { get; set; }
         
      
    }
}
