//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// app_version Entity Model
    /// </summary>    
   
    public class app_version
    {
        /// <summary>
        /// 主键，自增
        /// </summary>

        public int Id { get; set; }
    
        /// <summary>
        /// 版本状态1,需要升级，2 强制升级 0最新版本
        /// </summary>

        public int VersionStatus { get; set; }
    
        /// <summary>
        /// 版本消息
        /// </summary>

        public string VersionMsg { get; set; }
    
        /// <summary>
        /// 下载地址
        /// </summary>

        public string DownloadUrl { get; set; }
    
        /// <summary>
        /// app版本号
        /// </summary>

        public string AppVersion { get; set; }
    
        /// <summary>
        /// 版本记录号
        /// </summary>

        public int VersionCode { get; set; }
    
        /// <summary>
        /// app平台产品(appios, appandroid)
        /// </summary>

        public string Platform { get; set; }
    }
}
