//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// bank_bin Entity Model
    /// </summary>    
   
    public class bank_bin
    {
        /// <summary>
        /// 
        /// </summary>

        public long BIN { get; set; }
    
        /// <summary>
        /// 银行名称
        /// </summary>

        public string BankName { get; set; }
    
        /// <summary>
        /// 银行组织机构代码
        /// </summary>

        public string BankCode { get; set; }
    
        /// <summary>
        /// 银行卡名称
        /// </summary>

        public string CardName { get; set; }
    
        /// <summary>
        /// 银行卡类型
        /// </summary>

        public string CardType { get; set; }
    
        /// <summary>
        /// 银行卡类型code：01-借记卡，02-贷记卡，03-准贷借卡，04-预付卡
        /// </summary>

        public string CardTypeCode { get; set; }
    }
}
