//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// bill_wangshang Entity Model
    /// </summary>    
   
    public class bill_wangshang
    {
        /// <summary>
        /// 主键自增
        /// </summary>

        public long Id { get; set; }
    
        /// <summary>
        /// 网商商户号
        /// </summary>

        public string OutMerchantId { get; set; }
    
        /// <summary>
        /// 银行订单号
        /// </summary>

        public string OutOrderId { get; set; }
    
        /// <summary>
        /// 合作机构订单号
        /// </summary>

        public string OrderId { get; set; }
    
        /// <summary>
        /// 交易类型
        /// </summary>

        public string TradeType { get; set; }
    
        /// <summary>
        /// 货币种类
        /// </summary>

        public string Currency { get; set; }
    
        /// <summary>
        /// 交易金额
        /// </summary>

        public decimal TotalPay { get; set; }
    
        /// <summary>
        /// 手续费费率
        /// </summary>

        public decimal Rate { get; set; }
    
        /// <summary>
        /// 手续费
        /// </summary>

        public decimal Fee { get; set; }
    
        /// <summary>
        /// 清算金额（实际到账）
        /// </summary>

        public decimal TotalReceipt { get; set; }
    
        /// <summary>
        /// 原银行订单号(退款或撤销时出现)
        /// </summary>

        public string MerchantTradeNo { get; set; }
    
        /// <summary>
        /// 订单完成时间
        /// </summary>

        public DateTime PayTime { get; set; }
    
        /// <summary>
        /// 备注
        /// </summary>

        public string Remark { get; set; }
    
        /// <summary>
        /// 分账类型T0T1
        /// </summary>

        public string SettleType { get; set; }
    
        /// <summary>
        /// 支付渠道WX，ALI
        /// </summary>

        public string PayType { get; set; }
    
        /// <summary>
        /// ISV费用
        /// </summary>

        public decimal IsvFee { get; set; }
    }
}
