//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// isv_rate Entity Model
    /// </summary>    
   
    public class isv_rate
    {
        /// <summary>
        /// 主键自增
        /// </summary>

        public int Id { get; set; }
    
        /// <summary>
        /// 服务商UserId
        /// </summary>

        public long UserId { get; set; }
    
        /// <summary>
        /// 费率Key
        /// </summary>

        public string ConfigKey { get; set; }
    
        /// <summary>
        /// 费率名称 微信，支付宝，银行卡，花呗等
        /// </summary>

        public string ConfigName { get; set; }
    
        /// <summary>
        /// 费率
        /// </summary>

        public decimal ConfigValue { get; set; }
    
        /// <summary>
        /// 添加时间
        /// </summary>

        public DateTime CreationTime { get; set; }
    }
}
