//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// p_bank Entity Model
    /// </summary>    
   
    public class p_bank
    {
        /// <summary>
        /// 支行数据表
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 银行编号
        /// </summary>

        public string parent_bank_no { get; set; }
    
        /// <summary>
        /// 银行名称
        /// </summary>

        public string parent_bank_name { get; set; }
    
        /// <summary>
        /// 快速到账联行号
        /// </summary>

        public string quick_union_bank_no { get; set; }
    
        /// <summary>
        /// 支行名称
        /// </summary>

        public string bank_name { get; set; }
    
        /// <summary>
        /// 支行编号
        /// </summary>

        public string union_bank_no { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string city_code { get; set; }
    
        /// <summary>
        /// 地址
        /// </summary>

        public string address { get; set; }
    
        /// <summary>
        /// 邮编
        /// </summary>

        public string post_code { get; set; }
    
        /// <summary>
        /// 是否使用状态，1使用，2不使用
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        /// 外链所在城市id
        /// </summary>

        public int city_id { get; set; }
    
        /// <summary>
        /// 外链总行id
        /// </summary>

        public int bankparent_id { get; set; }
    }
}
