//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// p_bank_parent Entity Model
    /// </summary>    
   
    public class p_bank_parent
    {
        /// <summary>
        /// 银行数据表
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 银行编号
        /// </summary>

        public string parent_bank_no { get; set; }
    
        /// <summary>
        /// 银行名称
        /// </summary>

        public string parent_bank_name { get; set; }
    
        /// <summary>
        /// 快捷联行号
        /// </summary>

        public string union_bank_no { get; set; }
    
        /// <summary>
        /// 是否使用状态，1使用，2不使用
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        /// 威富通银行编号
        /// </summary>

        public string parent_bank_no_swiftpass { get; set; }
    }
}
