//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// p_mcc Entity Model
    /// </summary>    
   
    public class p_mcc
    {
        /// <summary>
        /// 
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string remark { get; set; }
    
        /// <summary>
        /// 费率
        /// </summary>

        public string rate { get; set; }
    
        /// <summary>
        /// mcc代码
        /// </summary>

        public string code { get; set; }
    
        /// <summary>
        /// 细类
        /// </summary>

        public string secondname { get; set; }
    
        /// <summary>
        /// 大类
        /// </summary>

        public string firstname { get; set; }
    
        /// <summary>
        /// 范围
        /// </summary>

        public string name { get; set; }
    
        /// <summary>
        /// 外链关联微信行业类目
        /// </summary>

        public int mccwx_id { get; set; }
    }
}
