//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// ser_merchant_coupon Entity Model
    /// </summary>    
   
    public class ser_merchant_coupon
    {
        /// <summary>
        /// 自动编号
        /// </summary>

        public long Id { get; set; }
    
        /// <summary>
        /// 商户号
        /// </summary>

        public long MerchantId { get; set; }
    
        /// <summary>
        /// 门店号
        /// </summary>

        public string ShopId { get; set; }
    
        /// <summary>
        /// 商品编号名称,只能有一个编号，eg 1008 对应口碑券的商品ID
        /// </summary>

        public string GoodsCode { get; set; }
    
        /// <summary>
        /// 券名称（商品名称）
        /// </summary>

        public string Coupon { get; set; }
    
        /// <summary>
        /// 券描述
        /// </summary>

        public string CouponDes { get; set; }
    
        /// <summary>
        /// 面值
        /// </summary>

        public decimal OrgPrice { get; set; }
    
        /// <summary>
        /// 价格
        /// </summary>

        public decimal RealPrice { get; set; }
    
        /// <summary>
        /// 状态 1 已上架 -1 已下架 0创建待审核
        /// </summary>

        public int Status { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>

        public DateTime CreationTime { get; set; }
    
        /// <summary>
        /// 排序
        /// </summary>

        public int Sort { get; set; }
    }
}
