//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_merchant_channel Entity Model
    /// </summary>    
   
    public class sys_merchant_channel
    {
        /// <summary>
        /// 主键，自增
        /// </summary>

        public int Id { get; set; }
    
        /// <summary>
        /// 是否可用  0 可用    1不可用
        /// </summary>

        public int is_enable { get; set; }
    
        /// <summary>
        /// 通道id
        /// </summary>

        public int channel_id { get; set; }
    
        /// <summary>
        /// 通道类型   1网商  2富友  3兴业  4银联  5付费通 6官方直连
        /// </summary>

        public int channel_type { get; set; }
    
        /// <summary>
        /// 通道名称
        /// </summary>

        public string channel_name { get; set; }
    
        /// <summary>
        /// 通道查询单号
        /// </summary>

        public string channel_order_id { get; set; }
    
        /// <summary>
        /// 微信商户模式（0托管服务商，1子商户独立）
        /// </summary>

        public int wx_mode { get; set; }
    
        /// <summary>
        /// 通道商户号
        /// </summary>

        public string mch_id { get; set; }
    
        /// <summary>
        /// 微信子商户号（官方直连通道微信子商户号和mch_id一致）
        /// </summary>

        public string wx_mch_id { get; set; }
    
        /// <summary>
        /// 商户appid
        /// </summary>

        public string wx_appid { get; set; }
    
        /// <summary>
        /// 商户appsecret
        /// </summary>

        public string wx_appsecret { get; set; }
    
        /// <summary>
        /// 小程序appid
        /// </summary>

        public string mini_appid { get; set; }
    
        /// <summary>
        /// 微信费率  扫码支付，二维码支付,JS支付,wap支付,app支付，小程序支付
        /// </summary>

        public string wx_rate { get; set; }
    
        /// <summary>
        /// 支付宝费率  扫码支付，二维码支付,JS支付,wap支付,app支付，小程序支付
        /// </summary>

        public string ali_rate { get; set; }
    
        /// <summary>
        /// 服务商机构号/服务商商户号
        /// </summary>

        public string serv_instno { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string serv_appid { get; set; }
    
        /// <summary>
        /// 服务商key
        /// </summary>

        public string serv_key { get; set; }
    
        /// <summary>
        /// 二级机构号
        /// </summary>

        public string serv_sub_instno { get; set; }
    
        /// <summary>
        /// 服务商appid
        /// </summary>

        public string wx_serv_appid { get; set; }
    
        /// <summary>
        /// 服务商appsecret
        /// </summary>

        public string wx_serv_appsecret { get; set; }
    
        /// <summary>
        /// 通道方审核状态  0 审核中  1审核通过  2审核驳回
        /// </summary>

        public int reviewed_status { get; set; }
    
        /// <summary>
        /// 通道方驳回原因
        /// </summary>

        public string reviewed_reason { get; set; }
    
        /// <summary>
        /// 是否绿洲商户 ：0非绿洲  1绿洲已提交 2绿洲已生效
        /// </summary>

        public int green_status { get; set; }
    
        /// <summary>
        /// 绿洲商户审核结果
        /// </summary>

        public string green_reviewedreason { get; set; }
    
        /// <summary>
        /// 是否参与蓝海计划:0未参与  1已申请/已驳回 2已生效 3已提交
        /// </summary>

        public int bluesea_status { get; set; }
    
        /// <summary>
        /// 蓝海商户审核结果
        /// </summary>

        public string bluesea_reviewedreason { get; set; }
    
        /// <summary>
        /// 阿里appid
        /// </summary>

        public string ali_appid { get; set; }
    
        /// <summary>
        /// 支付宝-官方-token
        /// </summary>

        public string ali_token { get; set; }
    
        /// <summary>
        /// 口碑外部门店编号
        /// </summary>

        public string ali_outerid { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string ali_pid { get; set; }
    
        /// <summary>
        /// 商户id
        /// </summary>

        public int merchantid { get; set; }
    }
}
