//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_channel Entity Model
    /// </summary>    
   
    public class sys_channel
    {
        /// <summary>
        /// 通道表
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 通道名称
        /// </summary>

        public string channelname { get; set; }
    
        /// <summary>
        /// 通道状态（0 正常；1 关闭；99 删除）
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        /// 通道类型（1 收呗；2 第三方）
        /// </summary>

        public int type { get; set; }
    
        /// <summary>
        /// 通道入网时间
        /// </summary>

        public DateTime createtime { get; set; }
    
        /// <summary>
        /// 通道支付类型（ 1网商  2富友  3兴业  4银联  5付费通 6官方直连）
        /// </summary>

        public int paytype { get; set; }
    
        /// <summary>
        /// 微信appid
        /// </summary>

        public string wx_serv_appid { get; set; }
    
        /// <summary>
        /// 微信secret
        /// </summary>

        public string wx_serv_secret { get; set; }
    
        /// <summary>
        /// 微信服务商商户号（官方通道）
        /// </summary>

        public string wx_mchid { get; set; }
    
        /// <summary>
        /// 微信服务商key（官方通道）
        /// </summary>

        public string wx_key { get; set; }
    
        /// <summary>
        /// 系统商签约协议的PID
        /// </summary>

        public string ali_isv_pid { get; set; }
    
        /// <summary>
        /// 支付宝分配给开发者的应用ID，扫呗2016081501751688
        /// </summary>

        public string ali_isv_appid { get; set; }
    
        /// <summary>
        /// 间联通道服务商机构号
        /// </summary>

        public string inst_no { get; set; }
    
        /// <summary>
        /// 间联通道服务商key
        /// </summary>

        public string inst_key { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string inst_appid { get; set; }
    
        /// <summary>
        /// 微信-( 刷卡成本,扫码成本，js成本，wap成本，app成本，小程序成本）
        /// </summary>

        public string wx_profit_rate { get; set; }
    
        /// <summary>
        /// 支付宝-( 刷卡成本,扫码成本，js成本，wap成本，app成本）
        /// </summary>

        public string ali_profit_rate { get; set; }
    
        /// <summary>
        /// 平台信用卡成本费率  万分比
        /// </summary>

        public int platform_creditcard_profit_rate { get; set; }
    
        /// <summary>
        /// 平台储蓄卡封顶费用（分）
        /// </summary>

        public int platform_debitcard_top_fee { get; set; }
    
        /// <summary>
        /// 平台储蓄卡成本费率  万分比
        /// </summary>

        public int platform_debitcard_profit_rate { get; set; }
    }
}
