//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_roles Entity Model
    /// </summary>    
   
    public class sys_roles
    {
        /// <summary>
        /// 主键ID
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 角色名
        /// </summary>

        public string rolename { get; set; }
    }
}
