//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_merchant Entity Model
    /// </summary>    
  
    public class sys_merchant
    {
        /// <summary>
        /// 商户基本信息表
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 商户状态  0 正常  1审核中  9审核驳回 10商户预审通过 98关停 99 关闭
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        /// 收呗商户号   固定6开头日期去掉20 ： 61807230100001
        /// </summary>

        public string merchant_no { get; set; }
    
        /// <summary>
        /// 银联商户号
        /// </summary>

        public string merchant_no_uni { get; set; }
    
        /// <summary>
        /// 商户名称
        /// </summary>

        public string merchant_name { get; set; }
    
        /// <summary>
        /// 商户简称
        /// </summary>

        public string merchant_alias { get; set; }
    
        /// <summary>
        /// 商户签约公司名称（公章名称）营业执照名称
        /// </summary>

        public string merchant_company { get; set; }
    
        /// <summary>
        /// 是否开通酷分积分： 0 未开通  1 已开通  2禁用
        /// </summary>

        public int coolfen_status { get; set; }
    
        /// <summary>
        /// 是否开通酷分活动（0 未开通；1 已开通）
        /// </summary>

        public int coolfen_activity { get; set; }
    
        /// <summary>
        /// 商户类型，0未知，1企业，2个体工商户，3小微商户
        /// </summary>

        public int merchant_business_type { get; set; }
    
        /// <summary>
        /// 微信一级类目id
        /// </summary>

        public int merchantwx1id { get; set; }
    
        /// <summary>
        /// 微信二级类目id
        /// </summary>

        public int merchantwx2id { get; set; }
    
        /// <summary>
        /// 微信三级类目id
        /// </summary>

        public int merchantwx3id { get; set; }
    
        /// <summary>
        /// 微信三级类目名称
        /// </summary>

        public string merchantwxname { get; set; }
    
        /// <summary>
        /// 微信经营范围三级类目代码
        /// </summary>

        public string merchantwxbusiness { get; set; }
    
        /// <summary>
        /// 商户签约负责人
        /// </summary>

        public string merchant_person { get; set; }
    
        /// <summary>
        /// 商户签约负责人电话
        /// </summary>

        public string merchant_phone { get; set; }
    
        /// <summary>
        /// 客服电话
        /// </summary>

        public string customer_servicephone { get; set; }
    
        /// <summary>
        /// 商户负责人邮箱
        /// </summary>

        public string merchant_email { get; set; }
    
        /// <summary>
        /// 商户签约地址
        /// </summary>

        public string merchant_address { get; set; }
    
        /// <summary>
        /// 所在省
        /// </summary>

        public string merchant_province { get; set; }
    
        /// <summary>
        /// 省code
        /// </summary>

        public string province_code { get; set; }
    
        /// <summary>
        /// 所在市
        /// </summary>

        public string merchant_city { get; set; }
    
        /// <summary>
        /// 市code
        /// </summary>

        public string city_code { get; set; }
    
        /// <summary>
        /// 区县名称
        /// </summary>

        public string merchant_county { get; set; }
    
        /// <summary>
        /// 区县code
        /// </summary>

        public string county_code { get; set; }
    
        /// <summary>
        /// 证件类型：0营业执照，1三证合一 2手持身份证照  9未知
        /// </summary>

        public int license_type { get; set; }
    
        /// <summary>
        /// 证件号码
        /// </summary>

        public string license_no { get; set; }
    
        /// <summary>
        /// 证件到期日（格式YYYY-MM-DD）
        /// </summary>

        public DateTime license_expire { get; set; }
    
        /// <summary>
        /// 证件类型，0身份证,1护照,2军官证,3士兵证,4回乡证,5户口本,6其他
        /// </summary>

        public int idtype { get; set; }
    
        /// <summary>
        /// 负责人身份证号
        /// </summary>

        public string idnum { get; set; }
    
        /// <summary>
        /// 负责人身份证有效期  格式yyyyMMdd
        /// </summary>

        public string idnumexpire { get; set; }
    
        /// <summary>
        /// 账户类型，1对公，2对私
        /// </summary>

        public int accounttype { get; set; }
    
        /// <summary>
        /// 银行账号绑定手机号
        /// </summary>

        public string accountphone { get; set; }
    
        /// <summary>
        /// 法人名称
        /// </summary>

        public string legalname { get; set; }
    
        /// <summary>
        /// 法人身份证号
        /// </summary>

        public string legal_idnum { get; set; }
    
        /// <summary>
        /// 法人身份证有效期  格式yyyy-MM-dd
        /// </summary>

        public DateTime legal_idnum_expire { get; set; }
    
        /// <summary>
        /// 结算类型:1.法人结算 2.非法人结算
        /// </summary>

        public int settlement_type { get; set; }
    
        /// <summary>
        /// 账户名
        /// </summary>

        public string cardname { get; set; }
    
        /// <summary>
        /// 开户行
        /// </summary>

        public string cardbankparent { get; set; }
    
        /// <summary>
        /// 开户行省份编号
        /// </summary>

        public string cardbankprovince { get; set; }
    
        /// <summary>
        /// 开户行城市编号
        /// </summary>

        public string cardbankcity { get; set; }
    
        /// <summary>
        /// 开户行-支行
        /// </summary>

        public string cardbank { get; set; }
    
        /// <summary>
        /// 卡号
        /// </summary>

        public string cardnum { get; set; }
    
        /// <summary>
        /// 联行号
        /// </summary>

        public string cardunionbankno { get; set; }
    
        /// <summary>
        /// 快捷联行号
        /// </summary>

        public string cardquickbankno { get; set; }
    
        /// <summary>
        ///  信用卡支付 0,不限制 1,限制
        /// </summary>

        public int no_credit { get; set; }
    
        /// <summary>
        /// yyyy-MM-dd HH:mm:ss 创建时间
        /// </summary>

        public DateTime createtime { get; set; }
    
        /// <summary>
        /// 更新时间,yyyy-MM-dd HH:mm:ss
        /// </summary>

        public DateTime updatetime { get; set; }
    
        /// <summary>
        /// 审核通过时间
        /// </summary>

        public DateTime reviewedtime { get; set; }
    
        /// <summary>
        /// 审核失败原因
        /// </summary>

        public string reviewedreason { get; set; }
    
        /// <summary>
        /// 操作员名称
        /// </summary>

        public string @operator { get; set; }
    
        /// <summary>
        /// 操作员id
        /// </summary>

        public int operatorid { get; set; }
    
        /// <summary>
        /// 渠道类型：1收呗 2其他渠道
        /// </summary>

        public int insttype { get; set; }
    
        /// <summary>
        /// 渠道号(关联渠道表）
        /// </summary>

        public string instno { get; set; }
    
        /// <summary>
        /// 微信支付总开关（0 未开通；1 已开通）
        /// </summary>

        public int wx_switch { get; set; }
    
        /// <summary>
        /// 支付宝支付总开关（0 未开通；1 已开通）
        /// </summary>

        public int ali_switch { get; set; }
    
        /// <summary>
        /// 关联商户通道配置表
        /// </summary>

        public int wx_channel_id { get; set; }
    
        /// <summary>
        /// 支付宝关联商户通道配置表
        /// </summary>

        public int ali_channel_id { get; set; }
    
        /// <summary>
        /// 关联商户图片表
        /// </summary>

        public int uploadid { get; set; }
    
        /// <summary>
        /// 关联bd业务员id
        /// </summary>

        public int bdid { get; set; }
    
        /// <summary>
        /// 代理商id
        /// </summary>

        public int agent1id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public int agent2id { get; set; }
    }
}
