//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_bd Entity Model
    /// </summary>    
   
    public class sys_bd
    {
        /// <summary>
        /// 
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// bd名称
        /// </summary>

        public string name { get; set; }
    
        /// <summary>
        /// bd代码
        /// </summary>

        public string code { get; set; }
    
        /// <summary>
        /// bd手机号
        /// </summary>

        public string phone { get; set; }
    
        /// <summary>
        /// 身份证号码
        /// </summary>

        public string idnum { get; set; }
    
        /// <summary>
        /// 0 正常  99删除
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        ///  创建时间
        /// </summary>

        public DateTime createtime { get; set; }
    
        /// <summary>
        /// 上级用户id
        /// </summary>

        public int agentid { get; set; }
    }
}
