//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_terminal Entity Model
    /// </summary>    
   
    public class sys_terminal
    {
        /// <summary>
        /// 终端信息
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 终端号
        /// </summary>

        public string terminal_no { get; set; }
    
        /// <summary>
        /// 银行卡终端号
        /// </summary>

        public string terminal_no_uni { get; set; }
    
        /// <summary>
        /// 激活码系统生成
        /// </summary>

        public string serial_num { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>

        public string create_time { get; set; }
    
        /// <summary>
        /// 品牌 如百富 嘉联 新国都
        /// </summary>

        public string terminal_brand { get; set; }
    
        /// <summary>
        /// 型号 如 百富S58
        /// </summary>

        public string terminal_model { get; set; }
    
        /// <summary>
        /// 机器号
        /// </summary>

        public string terminal_mac { get; set; }
    
        /// <summary>
        /// 二维码支付显示LOGO
        /// </summary>

        public string pay_logo { get; set; }
    
        /// <summary>
        /// 静态二维码支付显示名称
        /// </summary>

        public string pay_name { get; set; }
    
        /// <summary>
        /// 所属类型  1 智能POS机  2 收银插件 3静态码台卡  4收银盒子 5 接口 
        /// </summary>

        public int type { get; set; }
    
        /// <summary>
        /// 0 未激活 1 已激活  2已解绑  
        /// </summary>

        public int activation { get; set; }
    
        /// <summary>
        /// 0 正常   1未开通   99 删除  
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        /// 支付宝url
        /// </summary>

        public string alipayqrcode { get; set; }
    
        /// <summary>
        /// js支付开关 0 开   1关
        /// </summary>

        public int jspaystatus { get; set; }
    
        /// <summary>
        /// 扫码开关（预支付） 0开 1关
        /// </summary>

        public int prepaystatus { get; set; }
    
        /// <summary>
        /// 刷卡开关   0开    1关
        /// </summary>

        public int barpaystatus { get; set; }
    
        /// <summary>
        /// 关联门店id
        /// </summary>

        public int store_id { get; set; }
    
        /// <summary>
        /// 关联门店code
        /// </summary>

        public string store_code { get; set; }
    
        /// <summary>
        /// 门店名称
        /// </summary>

        public string store_name { get; set; }
    
        /// <summary>
        /// 外链商户id
        /// </summary>

        public int merchant_id { get; set; }
    
        /// <summary>
        /// MQTT协议推送开关 , 1为关闭，0为打开
        /// </summary>

        public int pushstatus { get; set; }
    }
}
