//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_users_log Entity Model
    /// </summary>    
   
    public class sys_users_log
    {
        /// <summary>
        /// 主键ID
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 用户名
        /// </summary>

        public string username { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>

        public string createtime { get; set; }
    
        /// <summary>
        /// 昵称
        /// </summary>

        public string nickname { get; set; }
    
        /// <summary>
        /// 用户密码
        /// </summary>

        public string password { get; set; }
    
        /// <summary>
        /// 服务密码（用于退款）
        /// </summary>

        public string servicepassword { get; set; }
    
        /// <summary>
        /// 头像地址
        /// </summary>

        public string headpicurl { get; set; }
    
        /// <summary>
        /// 0 正常  98封停 99删除
        /// </summary>

        public int status { get; set; }
    
        /// <summary>
        /// 邮箱
        /// </summary>

        public string email { get; set; }
    
        /// <summary>
        /// 电话
        /// </summary>

        public string phone { get; set; }
    
        /// <summary>
        /// 上次登录终端类型  0pc  1手机
        /// </summary>

        public int lastype { get; set; }
    
        /// <summary>
        /// 上次登录时间
        /// </summary>

        public string lasttime { get; set; }
    
        /// <summary>
        /// 上次登录ip
        /// </summary>

        public string lastip { get; set; }
    
        /// <summary>
        /// 关联其他的表的id  根据角色来区分具体是哪个表
        /// </summary>

        public int fid { get; set; }
    
        /// <summary>
        /// 所属商户id
        /// </summary>

        public int mid { get; set; }
    
        /// <summary>
        /// 证件号码
        /// </summary>

        public string idnum { get; set; }
    
        /// <summary>
        /// 0  系统创建  1 手动创建
        /// </summary>

        public int type { get; set; }
    
        /// <summary>
        /// 操作员
        /// </summary>

        public string operator { get; set; }
    
        /// <summary>
        /// 外键关联角色
        /// </summary>

        public int roles_id { get; set; }
    
        /// <summary>
        /// 环信开通状态：0，未开通；1，开通
        /// </summary>

        public int hx_status { get; set; }
    }
}
