//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_module Entity Model
    /// </summary>    
   
    public class sys_module
    {
        /// <summary>
        /// 
        /// </summary>

        public int Id { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public int ParentId { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string EnCode { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string Name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string Icon { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string UrlAddress { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string OpenTarget { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public bool IsMenu { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public bool IsExpand { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public bool IsPublic { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public int SortCode { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public string Description { get; set; }
    
        /// <summary>
        /// 
        /// </summary>

        public bool IsEnabled { get; set; }
    }
}
