//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// sys_merchant_uploadfile Entity Model
    /// </summary>    
   
    public class sys_merchant_uploadfile
    {
        /// <summary>
        /// 证照信息
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 营业执照(或持件人照片)
        /// </summary>

        public string p01 { get; set; }
    
        /// <summary>
        /// 法人代表身份证正面
        /// </summary>

        public string p02 { get; set; }
    
        /// <summary>
        /// 法人代表身份证反面
        /// </summary>

        public string p03 { get; set; }
    
        /// <summary>
        /// 银行卡正面
        /// </summary>

        public string p04 { get; set; }
    
        /// <summary>
        /// 银行卡反面
        /// </summary>

        public string p05 { get; set; }
    
        /// <summary>
        /// 门头照片
        /// </summary>

        public string p06 { get; set; }
    
        /// <summary>
        /// 内部前台照片
        /// </summary>

        public string p07 { get; set; }
    
        /// <summary>
        /// 三联单合同照片
        /// </summary>

        public string p08 { get; set; }
    
        /// <summary>
        /// 其他证明材料（选填）
        /// </summary>

        public string p09 { get; set; }
    
        /// <summary>
        /// 手持身份证
        /// </summary>

        public string p10 { get; set; }
    
        /// <summary>
        /// 开户许可证照片
        /// </summary>

        public string p11 { get; set; }
    
        /// <summary>
        /// 组织机构代码证照片
        /// </summary>

        public string p12 { get; set; }
    
        /// <summary>
        /// 税务登记证照片
        /// </summary>

        public string p13 { get; set; }
    
        /// <summary>
        /// 入账非法人证明照片
        /// </summary>

        public string p14 { get; set; }
    
        /// <summary>
        /// 对私账户身份证正面照片
        /// </summary>

        public string p15 { get; set; }
    
        /// <summary>
        /// 对私账户身份证反面照片
        /// </summary>

        public string p16 { get; set; }
    
        /// <summary>
        /// 商户总分店关系证明
        /// </summary>

        public string p17 { get; set; }
    
        /// <summary>
        /// 商户增值协议照片
        /// </summary>

        public string p18 { get; set; }
    
        /// <summary>
        /// 分账承诺函
        /// </summary>

        public string p19 { get; set; }
    
        /// <summary>
        /// 微信支付物料照片
        /// </summary>

        public string p20 { get; set; }
    
        /// <summary>
        /// 第三方平台截图（绿洲）
        /// </summary>

        public string p21 { get; set; }
    
        /// <summary>
        /// 支付宝支付物料照片
        /// </summary>

        public string p22 { get; set; }
    }
}
