//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2018-08-09 23:01:48 by 大聪哥
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace T4.Entities
{
    /// <summary>
    /// t_trade_order Entity Model
    /// </summary>    
   
    public class t_trade_order
    {
        /// <summary>
        /// 
        /// </summary>

        public int id { get; set; }
    
        /// <summary>
        /// 类型   100银行卡刷卡  300 支付宝 400微信 500口碑
        /// </summary>

        public int type { get; set; }
    
        /// <summary>
        /// 一级代理id
        /// </summary>

        public int agent1_id { get; set; }
    
        /// <summary>
        /// 二级代理id
        /// </summary>

        public int agent2_id { get; set; }
    
        /// <summary>
        /// 业务员id
        /// </summary>

        public int bd_id { get; set; }
    
        /// <summary>
        /// 门店id
        /// </summary>

        public int shop_id { get; set; }
    
        /// <summary>
        /// 门店code
        /// </summary>

        public string shop_code { get; set; }
    
        /// <summary>
        /// 门店名称
        /// </summary>

        public string shop_name { get; set; }
    
        /// <summary>
        /// 支付方式 刷卡支付1，扫码支付2，公众号支付3，wap支付4 ,app支付5 ，小程序支付6 ，刷脸支付7       
        /// </summary>

        public int pay_mode { get; set; }
    
        /// <summary>
        /// 通道类型  1网商  2富友  3兴业  4银联  5付费通 6官方直连
        /// </summary>

        public int channel_type { get; set; }
    
        /// <summary>
        /// 所属通道id
        /// </summary>

        public int channel_id { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>

        public DateTime create_time { get; set; }
    
        /// <summary>
        /// 创建日期
        /// </summary>

        public DateTime create_date { get; set; }
    
        /// <summary>
        /// 结算处理时间
        /// </summary>

        public DateTime settle_time { get; set; }
    
        /// <summary>
        /// 结算处理日期
        /// </summary>

        public DateTime settle_date { get; set; }
    
        /// <summary>
        /// 机构号
        /// </summary>

        public string inst_no { get; set; }
    
        /// <summary>
        /// 商户id
        /// </summary>

        public int merchant_id { get; set; }
    
        /// <summary>
        /// pos端商户号
        /// </summary>

        public string merchant_no { get; set; }
    
        /// <summary>
        /// 商户名称
        /// </summary>

        public string merchant_name { get; set; }
    
        /// <summary>
        /// 终端号
        /// </summary>

        public string terminal_no { get; set; }
    
        /// <summary>
        /// 请求流水号
        /// </summary>

        public string pay_trace_no { get; set; }
    
        /// <summary>
        /// 请求交易时间
        /// </summary>

        public string pay_time { get; set; }
    
        /// <summary>
        /// 订单号
        /// </summary>

        public string out_trade_no { get; set; }
    
        /// <summary>
        /// 退款单号
        /// </summary>

        public string out_refund_no { get; set; }
    
        /// <summary>
        /// 总金额(单位分)
        /// </summary>

        public int total_fee { get; set; }
    
        /// <summary>
        /// 退款(单位分)
        /// </summary>

        public int refund_fee { get; set; }
    
        /// <summary>
        /// 手续费费率万分比
        /// </summary>

        public int rate { get; set; }
    
        /// <summary>
        /// 手续费 单位分
        /// </summary>

        public int fee { get; set; }
    
        /// <summary>
        /// 结余金额(分)，用作统计,支付成功为支付金额，支付失败和支付中为0，有退款为支付金额-退款金额
        /// </summary>

        public int balance { get; set; }
    
        /// <summary>
        /// 商家实收金额
        /// </summary>

        public int receipt_fee { get; set; }
    
        /// <summary>
        /// 分润类型（  0结算  1不结算）
        /// </summary>

        public int profit_type { get; set; }
    
        /// <summary>
        /// 一级代理分润
        /// </summary>

        public int agent1_profit { get; set; }
    
        /// <summary>
        /// 二级代理分润
        /// </summary>

        public int agent2_profit { get; set; }
    
        /// <summary>
        /// 业务员分润
        /// </summary>

        public int bd_profit { get; set; }
    
        /// <summary>
        /// 支付状态，支付成功1，支付失败2，支付中3，已撤销4,  退款成功5  退款失败6 冲正7 退款中8
        /// </summary>

        public int pay_status_code { get; set; }
    
        /// <summary>
        /// 支付状态说明
        /// </summary>

        public string pay_status_msg { get; set; }
    
        /// <summary>
        /// 退款状态，退款成功01，退款失败02
        /// </summary>

        public string refund_status { get; set; }
    
        /// <summary>
        /// 退款状态说明
        /// </summary>

        public string refund_status_msg { get; set; }
    
        /// <summary>
        /// 操作员
        /// </summary>

        public string operator_id { get; set; }
    
        /// <summary>
        /// 退款操作员
        /// </summary>

        public string refund_operator_id { get; set; }
    
        /// <summary>
        /// 订单描述
        /// </summary>

        public string order_body { get; set; }
    
        /// <summary>
        /// 第三方通道方返回的错误码
        /// </summary>

        public string channel_result_code { get; set; }
    
        /// <summary>
        /// 第三方通道方返回的错误描述
        /// </summary>

        public string channel_result_msg { get; set; }
    
        /// <summary>
        /// 第三方通道返回的订单号（微信或者支付宝订单号）
        /// </summary>

        public string channel_trade_no { get; set; }
    
        /// <summary>
        /// 第三方购买方用户id（微信为openid）
        /// </summary>

        public string channel_user_id { get; set; }
    
        /// <summary>
        /// 支付用户所用银行卡类型
        /// </summary>

        public string channel_bank_type { get; set; }
    
        /// <summary>
        /// 银联商户号
        /// </summary>

        public string uni_merchant_no { get; set; }
    
        /// <summary>
        /// 银联终端号
        /// </summary>

        public string uni_terminal_id { get; set; }
    
        /// <summary>
        /// 银行卡号
        /// </summary>

        public string uni_card_no { get; set; }
    
        /// <summary>
        /// 银联卡支付订单号
        /// </summary>

        public string uni_order_no { get; set; }
    
        /// <summary>
        /// 0储蓄卡，1信用卡，2未知 
        /// </summary>

        public int card_type { get; set; }
    
        /// <summary>
        /// 通道支付订单号（网商订单号或者富友订单号）
        /// </summary>

        public string channel_order_no { get; set; }
    
        /// <summary>
        /// 交易完成时间
        /// </summary>

        public DateTime end_time { get; set; }
    
        /// <summary>
        /// 退款完成时间
        /// </summary>

        public DateTime refund_time { get; set; }
    
        /// <summary>
        /// 三方系统回调通知地址
        /// </summary>

        public string notify_url { get; set; }
    
        /// <summary>
        /// 交易优惠信息
        /// </summary>

        public string discount { get; set; }
    
        /// <summary>
        /// 三方系统保留字段
        /// </summary>

        public string attach { get; set; }
    
        /// <summary>
        /// 是否发送通知 0未发送，1已发送
        /// </summary>

        public int is_notice { get; set; }
    }
}
